Melhorado a identação do código

diff --git a/usr/share/adicli/base/db_engine b/usr/share/adicli/base/db_engine
--- a/usr/share/adicli/base/db_engine
+++ b/usr/share/adicli/base/db_engine
@@ -8,61 +8,61 @@
 
 case $db_engine in
 
-  #
-  # PostgreSQL
-  #
-  "postgres")
-    export PGPASSWORD="$db_password"
-    db_command="\d $db_table"
+    #
+    # PostgreSQL
+    #
+    "postgres")
+        export PGPASSWORD="$db_password"
+        db_command="\d $db_table"
 
-    if [ "X$db_table" != "X" ] ; then
-      db_connector="psql -h $db_host -p $db_port -d $db -U $db_admin -w"
-      PRIMARY_KEY=$(echo "$db_command"|$db_connector -a |grep -i 'PRIMARY KEY'|awk '{print $5}'|sed -e 's/(//g; s/)//g; s/,.*//g')
-      PRIMARYKEY=$PRIMARY_KEY
-    fi
+        if [ "X$db_table" != "X" ] ; then
+            db_connector="psql -h $db_host -p $db_port -d $db -U $db_admin -w"
+            PRIMARY_KEY=$(echo "$db_command"|$db_connector -a |grep -i 'PRIMARY KEY'|awk '{print $5}'|sed -e 's/(//g; s/)//g; s/,.*//g')
+            PRIMARYKEY=$PRIMARY_KEY
+        fi
 
-    db_connector="psql -h $db_host -p $db_port -d $db -U $db_admin -w -t"
-    show_tables="\dt"
-    ;;
+        db_connector="psql -h $db_host -p $db_port -d $db -U $db_admin -w -t"
+        show_tables="\dt"
+        ;;
 
-  #
-  # MySQL
-  #
-  "mysql")
-    db_command="desc $db_table;"
-    db_connector="mysql -s -h $db_host -P $db_port -u $db_admin -p$db_password $db"
+    #
+    # MySQL
+    #
+    "mysql")
+        db_command="desc $db_table;"
+        db_connector="mysql -s -h $db_host -P $db_port -u $db_admin -p$db_password $db"
 
-    if [ "X$db_table" != "X" ] ; then
-      PRIMARY_KEY=$(echo "SHOW KEYS FROM $db_table WHERE Key_name = 'PRIMARY';"|$db_connector|grep -i PRIMARY|awk '{print $5}')
-      PRIMARYKEY=$PRIMARY_KEY
-    fi
+        if [ "X$db_table" != "X" ] ; then
+            PRIMARY_KEY=$(echo "SHOW KEYS FROM $db_table WHERE Key_name = 'PRIMARY';"|$db_connector|grep -i PRIMARY|awk '{print $5}')
+            PRIMARYKEY=$PRIMARY_KEY
+        fi
 
-    show_tables="show tables;"
-    ;;
+        show_tables="show tables;"
+        ;;
 
-  #
-  # Firebird
-  #
-  "firebird")
-    db_command="show table $db_table;"
-    db_connector="isql-fb -u $db_admin -p $db_password $db_host/$db_port:$db"
+    #
+    # Firebird
+    #
+    "firebird")
+        db_command="show table $db_table;"
+        db_connector="isql-fb -u $db_admin -p $db_password $db_host/$db_port:$db"
 
-    if [ "X$db_table" != "X" ] ; then
-      PRIMARY_KEY=$(echo "$db_command"|$db_connector|grep -i "^  Primary key "|awk '{print $3}'|sed -e 's/(//g; s/)//g; s/,.*//g')
-      PRIMARYKEY=$PRIMARY_KEY
-    fi
+        if [ "X$db_table" != "X" ] ; then
+            PRIMARY_KEY=$(echo "$db_command"|$db_connector|grep -i "^  Primary key "|awk '{print $3}'|sed -e 's/(//g; s/)//g; s/,.*//g')
+            PRIMARYKEY=$PRIMARY_KEY
+        fi
 
-    show_tables="show tables;"
-    ;;
+        show_tables="show tables;"
+        ;;
 
-  #
-  # Invalid or Unknown database
-  #
-  *)
-    echo "$0: Error - Invalid or Unknown database"
-    usage
-    exit 255
-    ;;
+    #
+    # Invalid or Unknown database
+    #
+    *)
+        echo "$0: Error - Invalid or Unknown database"
+        usage
+        exit 255
+        ;;
 
 esac
 
diff --git a/usr/share/adicli/base/header b/usr/share/adicli/base/header
--- a/usr/share/adicli/base/header
+++ b/usr/share/adicli/base/header
@@ -9,9 +9,9 @@
 # Usage
 #
 usage() {
-  echo
-  echo "Use: $0 -c database.conf -t Table -T Template -M Model -C ClassName [-O tables|templates|examples]"
-  echo
+    echo
+    echo "Use: $0 -c database.conf -t Table -T Template -M Model -C ClassName [-O tables|templates|examples]"
+    echo
 }
 
 test() {
@@ -46,51 +46,51 @@ EOF
 # Command Line Options
 #
 while getopts :S:M:A:P:c:C:t:T:O: opt "${MY_OWN_SET[@]}"; do
-  case $opt in
-    S)
-      STRATEGY=$OPTARG
-      ;;
-    M)
-      MODEL=$OPTARG
-      ;;      
-    A)
-      AUTHOR=$OPTARG
-      ;;
-    P)
-      PARENT_CLASS=$OPTARG
-      ;;
-    c)
-      conf_file=$OPTARG
-      ;;
-    T)
-      TEMPLATE=$OPTARG
-      ;;
-    C)
-      CLASS=$OPTARG
-      ;;
-    O)
-      option=$(echo "$OPTARG"|tr '[:upper:]' '[:lower:]')
-      case $option in
-        "tables"|"templates"|"examples")
-        ;;
-        *)
-          echo "$0: Error - Invalid option ($OPTARG)"
-          exit 3
-        ;;
-      esac
-      ;;
-    t)
-      db_table="$OPTARG"
-      ;;
-    \?)
-      echo "Invalid option: -$OPTARG" >&2
-      exit 2
-      ;;
-    :)
-      echo "Option -$OPTARG requires an argument." >&2
-      exit 1
-      ;;
-  esac
+    case $opt in
+      S)
+          STRATEGY=$OPTARG
+          ;;
+      M)
+          MODEL=$OPTARG
+          ;;      
+      A)
+          AUTHOR=$OPTARG
+          ;;
+      P)
+          PARENT_CLASS=$OPTARG
+          ;;
+      c)
+          conf_file=$OPTARG
+          ;;
+      T)
+          TEMPLATE=$OPTARG
+          ;;
+      C)
+          CLASS=$OPTARG
+          ;;
+      O)
+          option=$(echo "$OPTARG"|tr '[:upper:]' '[:lower:]')
+          case $option in
+                  "tables"|"templates"|"examples")
+                  ;;
+              *)
+                  echo "$0: Error - Invalid option ($OPTARG)"
+                  exit 3
+              ;;
+          esac
+          ;;
+      t)
+          db_table="$OPTARG"
+          ;;
+      \?)
+          echo "Invalid option: -$OPTARG" >&2
+          exit 2
+          ;;
+      :)
+          echo "Option -$OPTARG requires an argument." >&2
+          exit 1
+          ;;
+    esac
 
 done
 
@@ -99,8 +99,8 @@ done
 # ==============================================================================
 if [ "X$1" == "X" ] ; then
 
-  usage
-  exit
+    usage
+    exit
 
 fi
 
@@ -108,39 +108,39 @@ fi
 # ==============================================================================
 if [ "X$option" != "X" ] ; then
 
-  echo
+    echo
 
 else
 
-  if [ -z "$conf_file" ] || [ ! -f "$conf_file" ]; then
+    if [ -z "$conf_file" ] || [ ! -f "$conf_file" ]; then
 
-    echo "$0: Error - Invalid database config file"
-    #exit 2
+        echo "$0: Error - Invalid database config file"
+        #exit 2
 
-  else
+    else
 
-    source "$conf_file"
+        source "$conf_file"
 
-  fi
+    fi
 
-  #
-  # Verifica se todos os parametros foram passados
-  #
-  if  [ -z "$db" ]            || \
-      [ -z "$db_host" ]       || \
-      [ -z "$db_engine" ]     || \
-      [ -z "$db_port" ]       || \
-      [ -z "$db_admin" ]      || \
-      [ -z "$db_password" ]   || \
-      [ -z "$db_table" ]      || \
-      [ -z "$MODEL" ]         || \
-      [ -z "$TEMPLATE" ]      || \
-      [ -z "$CLASS" ] ; then
+    #
+    # Verifica se todos os parametros foram passados
+    #
+    if  [ -z "$db" ]            || \
+        [ -z "$db_host" ]       || \
+        [ -z "$db_engine" ]     || \
+        [ -z "$db_port" ]       || \
+        [ -z "$db_admin" ]      || \
+        [ -z "$db_password" ]   || \
+        [ -z "$db_table" ]      || \
+        [ -z "$MODEL" ]         || \
+        [ -z "$TEMPLATE" ]      || \
+        [ -z "$CLASS" ] ; then
 
-    usage
-    exit
+        usage
+        exit
 
-  fi
+    fi
 
 fi
 
